// Optimize · pt-BR migration catalog batch 5
// Original project: laurentiu021/SystemManager · MIT License

namespace SysManager.Services;

/// <summary>
/// Remaining user-facing source templates. Runtime values are also handled by the pattern and
/// fallback catalogs after interpolation; keeping the source templates here makes the pt-BR
/// audit explicit and reviewable.
/// </summary>
public static class PtBrMigrationCatalog5
{
    private static readonly Dictionary<string, string> Exact = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Desktop ready-up:"] = "Área de Trabalho pronta:",
        ["Dark theme start time (HH:mm)"] = "Horário de início do tema escuro (HH:mm)",
        ["Light theme start time (HH:mm)"] = "Horário de início do tema claro (HH:mm)",
        ["Use 24-hour times, e.g. 19:00 and 07:00."] = "Use o formato de 24 horas, por exemplo 19:00 e 07:00.",
        ["Selected total:"] = "Total selecionado:",
        ["Current DNS:"] = "DNS atual:",
        ["List drivers"] = "Listar drivers",
        ["Folder:"] = "Pasta:",
        ["Other overlays (disable manually in each app):"] = "Outras sobreposições (desative manualmente em cada aplicativo):",
        ["Purge standby list"] = "Liberar memória em espera",
        ["Boot mode:"] = "Modo de inicialização:",
        ["Generate a full snapshot of this PC — OS, CPU, memory, GPU, motherboard, storage health, and network — then export it as text, HTML, or JSON. Read-only: nothing is changed and nothing leaves this machine."] = "Gere um retrato completo deste PC — Windows, CPU, memória, GPU, placa-mãe, saúde do armazenamento e rede — e exporte como texto, HTML ou JSON. Somente leitura: nada é alterado e nenhum dado sai desta máquina.",
        ["Error: {ex.Message}"] = "Erro: {ex.Message}",
        ["Health score: {r.Score}/100 ({r.Label})"] = "Pontuação de saúde: {r.Score}/100 ({r.Label})",
        ["Health check failed: {ex.Message}"] = "Falha na verificação de saúde: {ex.Message}",
        ["Cleanup failed: {ex.Message}"] = "Falha na limpeza: {ex.Message}",
        ["Display change failed: {ex.Message}"] = "Falha ao alterar a configuração de vídeo: {ex.Message}",
        ["File contents were securely overwritten, but the file could not be removed: {ex.Message}"] = "O conteúdo do arquivo foi sobrescrito com segurança, mas não foi possível remover o arquivo: {ex.Message}",
        ["File contents were securely overwritten, but removal was denied: {ex.Message}"] = "O conteúdo do arquivo foi sobrescrito com segurança, mas a remoção foi negada: {ex.Message}",
        ["{layersBad} network layers are showing trouble. Check the per-target stats to localize."] = "{layersBad} camadas da rede apresentam problemas. Consulte os dados de cada destino para localizar a causa.",
        ["{diskName} health degraded — consider backup"] = "Saúde de {diskName} degradada — considere fazer backup",
        ["High memory usage ({snapshot.Memory.UsedPercent:0}%) — close unused apps"] = "Uso alto de memória ({snapshot.Memory.UsedPercent:0}%) — feche aplicativos que não estão sendo usados",
        ["Battery wear {battery.WearPercent:0}% — consider replacement"] = "Desgaste da bateria em {battery.WearPercent:0}% — considere a substituição",
        ["Could not start service '{serviceName}': {ex.Message}"] = "Não foi possível iniciar o serviço '{serviceName}': {ex.Message}",
        ["Could not stop service '{serviceName}': {ex.Message}"] = "Não foi possível parar o serviço '{serviceName}': {ex.Message}",
        ["Memory API unavailable: {ex.Message}"] = "API de memória indisponível: {ex.Message}",
        ["{unhealthyDisk.FriendlyName} reports status: {unhealthyDisk.HealthStatus}. Consider backing up important data."] = "{unhealthyDisk.FriendlyName} informa o estado: {unhealthyDisk.HealthStatus}. Considere fazer backup dos dados importantes.",
        ["Network: {ex.Message}"] = "Rede: {ex.Message}",
        ["Error 0x{ex.HResult:X8}"] = "Erro 0x{ex.HResult:X8}",
        ["✗ COM error: 0x{ex.HResult:X8} {ex.Message}"] = "✗ Erro COM: 0x{ex.HResult:X8} {ex.Message}",
        ["Update available: {LatestVersionLabel} ({LatestPublishedLabel}). Click Download to get it."] = "Atualização disponível: {LatestVersionLabel} ({LatestPublishedLabel}). Clique em Baixar para obter a nova versão.",
        ["Network error — could not reach GitHub: {ex.Message}. Click Retry to try again."] = "Erro de rede — não foi possível acessar o GitHub: {ex.Message}. Clique em Tentar novamente.",
        ["Download failed: {ex.Message}. This usually means a network issue or firewall blocking the connection. Try 'Manual download' as fallback."] = "Falha no download: {ex.Message}. Isso normalmente indica problema de rede ou bloqueio pelo firewall. Tente 'Download manual' como alternativa.",
        ["Couldn't copy to clipboard: it's currently in use by another application."] = "Não foi possível copiar para a área de transferência: ela está sendo usada por outro aplicativo.",
        ["Failed to save report: {ex.Message}"] = "Falha ao salvar o relatório: {ex.Message}",
        ["Failed to save report (access denied): {ex.Message}"] = "Falha ao salvar o relatório (acesso negado): {ex.Message}",
        ["Failed to generate report: {ex.Message}"] = "Falha ao gerar o relatório: {ex.Message}",
        ["Cannot lock update file: {ex.Message}"] = "Não foi possível bloquear o arquivo de atualização: {ex.Message}",
        ["Cannot access update file: {ex.Message}"] = "Não foi possível acessar o arquivo de atualização: {ex.Message}",
        ["Update failed: {ex.Message}"] = "Falha na atualização: {ex.Message}",
        ["{AlertCount} applications found"] = "{AlertCount} aplicativos encontrados",
        ["Failed to read registry: {ex.Message}"] = "Falha ao ler o Registro: {ex.Message}",
        ["Unblocked {unblocked} application{(unblocked == 1 ?"] = "{unblocked} aplicativo(s) desbloqueado(s)",
        ["Saved preset \"{name}\" with {entries.Count} app{(entries.Count == 1 ?"] = "Predefinição \"{name}\" salva com {entries.Count} aplicativo(s)",
        ["{Battery.Name} · {Battery.ChargePercent}% · Health {Battery.HealthPercent}% · {Battery.Status}"] = "{Battery.Name} · {Battery.ChargePercent}% · Saúde {Battery.HealthPercent}% · {Battery.Status}",
        ["{Battery.Name} · {Battery.ChargePercent}% · Health: requires elevation · {Battery.Status}"] = "{Battery.Name} · {Battery.ChargePercent}% · Saúde: requer elevação · {Battery.Status}",
        ["WMI error: {ex.Message}"] = "Erro WMI: {ex.Message}",
        ["Failed: {ex.Message}"] = "Falha: {ex.Message}",
        ["{deleted} files removed."] = "{deleted} arquivos removidos.",
        ["Done. Installed: {installed}, Failed: {failed}."] = "Concluído. Instalados: {installed}, falhas: {failed}.",
        ["Installed: {installed}, Failed: {failed}"] = "Instalados: {installed}, falhas: {failed}",
        ["Scan failed: {ex.Message}"] = "Falha na análise: {ex.Message}",
        ["Check failed: {ex.Message}"] = "Falha na verificação: {ex.Message}",
        ["Last scan: {DateTime.Now:HH:mm:ss}"] = "Última análise: {DateTime.Now:HH:mm:ss}",
        ["Tune-Up error: {ex.Message}"] = "Erro na otimização rápida: {ex.Message}",
        ["Selected {n} commonly-removed app{(n == 1 ?"] = "{n} aplicativo(s) normalmente removido(s) selecionado(s)",
        ["[{p.Current}/{p.Total}]  {p.CategoryName}"] = "[{p.Current}/{p.Total}]  {p.CategoryName}",
        ["Clean failed: {ex.Message}"] = "Falha na limpeza: {ex.Message}",
        ["Found {list.Count} files ≥ {MinSizeMB} MB in {SelectedLocation.Label.Trim()}."] = "Encontrados {list.Count} arquivos ≥ {MinSizeMB} MB em {SelectedLocation.Label.Trim()}.",
        ["{list.Count} files found ≥ {MinSizeMB} MB"] = "{list.Count} arquivos encontrados ≥ {MinSizeMB} MB",
        ["Could not read Defender status: {ex.Message}"] = "Não foi possível ler o estado do Defender: {ex.Message}",
        ["Could not change Controlled Folder Access: {ex.Message}"] = "Não foi possível alterar o Acesso Controlado a Pastas: {ex.Message}",
        ["Could not add the exclusion: {ex.Message}"] = "Não foi possível adicionar a exclusão: {ex.Message}",
        ["Could not remove the exclusion: {ex.Message}"] = "Não foi possível remover a exclusão: {ex.Message}",
        ["Scanning folder {p.FoldersScanned}: {p.CurrentFolder}"] = "Analisando pasta {p.FoldersScanned}: {p.CurrentFolder}",
        ["Analysis failed: {ex.Message}"] = "Falha na análise: {ex.Message}",
        ["Error reading hosts file: {ex.Message}"] = "Erro ao ler o arquivo hosts: {ex.Message}",
        ["Failed to set DNS: {ex.Message}"] = "Falha ao configurar o DNS: {ex.Message}",
        ["Failed to reset DNS: {ex.Message}"] = "Falha ao redefinir o DNS: {ex.Message}",
        ["Failed to restore DNS: {ex.Message}"] = "Falha ao restaurar o DNS: {ex.Message}",
        ["Error saving hosts file: {ex.Message}"] = "Erro ao salvar o arquivo hosts: {ex.Message}",
        ["Error restoring hosts file: {ex.Message}"] = "Erro ao restaurar o arquivo hosts: {ex.Message}",
        ["Could not read status: {ex.Message}"] = "Não foi possível ler o estado: {ex.Message}",
        ["{component} operation failed: {ex.Message}"] = "Falha na operação de {component}: {ex.Message}",
        ["{completed} shredded, {failed} failed"] = "{completed} excluído(s) com segurança, {failed} falha(s)",
        ["Event log error:"] = "Erro no Log de Eventos:",
        ["Recommended action:"] = "Ação recomendada:",
        ["Export failed:"] = "Falha ao exportar:",
        ["{r.ToolName} completed successfully"] = "{r.ToolName} concluído com sucesso",
        ["✗ Error: {ex.Message}"] = "✗ Erro: {ex.Message}",
        ["Active plan: {Profile.ProfileSummary} ·"] = "Plano ativo: {Profile.ProfileSummary} ·",
        ["Read settings failed: {ex.Message}"] = "Falha ao ler as configurações: {ex.Message}",
        ["Power plan change failed: {ex.Message}"] = "Falha ao alterar o plano de energia: {ex.Message}",
        ["Visual effects change failed: {ex.Message}"] = "Falha ao alterar os efeitos visuais: {ex.Message}",
        ["Game Mode {(enabling ?"] = "Modo de Jogo {(enabling ?",
        ["Game Mode change failed: {ex.Message}"] = "Falha ao alterar o Modo de Jogo: {ex.Message}",
        ["Xbox Game Bar change failed: {ex.Message}"] = "Falha ao alterar a Xbox Game Bar: {ex.Message}",
        ["GPU max performance {(WantGpuMaxPerformance ?"] = "Desempenho máximo da GPU {(WantGpuMaxPerformance ?",
        ["GPU setting change failed: {ex.Message}"] = "Falha ao alterar a configuração da GPU: {ex.Message}",
        ["Processor state change failed: {ex.Message}"] = "Falha ao alterar o estado do processador: {ex.Message}",
        ["Restore point creation failed: {ex.Message}"] = "Falha ao criar o ponto de restauração: {ex.Message}",
        ["RAM trim failed: {ex.Message}"] = "Falha ao liberar memória de trabalho: {ex.Message}",
        ["Hibernation toggle failed: {ex.Message}"] = "Falha ao alterar a hibernação: {ex.Message}",
        ["Restore all settings failed: {ex.Message}"] = "Falha ao restaurar todas as configurações: {ex.Message}",
        ["⛔ \"{entry.Name}\" is a critical system process and cannot be ended —"] = "⛔ \"{entry.Name}\" é um processo crítico do sistema e não pode ser encerrado —",
        ["{ProcessCount} processes · {FormatSize(TotalMemory)} total memory"] = "{ProcessCount} processos · {FormatSize(TotalMemory)} de memória total",
        ["Export failed: {ex.Message}"] = "Falha ao exportar: {ex.Message}",
        ["Export failed (access denied): {ex.Message}"] = "Falha ao exportar (acesso negado): {ex.Message}",
        ["Import failed: {ex.Message}"] = "Falha ao importar: {ex.Message}",
        ["Import failed (access denied): {ex.Message}"] = "Falha ao importar (acesso negado): {ex.Message}",
        ["Section list refreshed."] = "Lista de seções atualizada.",
        ["Could not create a restore point: {ex.Message}"] = "Não foi possível criar um ponto de restauração: {ex.Message}",
        ["Restore this PC to:  #{point.SequenceNumber} — {point.Description} {point.CreatedDisplay}"] = "Restaurar este PC para: #{point.SequenceNumber} — {point.Description} {point.CreatedDisplay}",
        ["Could not start the restore: {ex.Message}"] = "Não foi possível iniciar a restauração: {ex.Message}",
        ["Maintenance is scheduled (state: {status.State})."] = "A manutenção está agendada (estado: {status.State}).",
        ["Service scan failed: {ex.Message}"] = "Falha ao analisar serviços: {ex.Message}",
        ["{TotalCount} services ({RunningCount} running)"] = "{TotalCount} serviços ({RunningCount} em execução)",
        ["Start service \"{entry.DisplayName}\"?"] = "Iniciar o serviço \"{entry.DisplayName}\"?",
        ["Start service failed: {ex.Message}"] = "Falha ao iniciar o serviço: {ex.Message}",
        ["⛔ \"{entry.DisplayName}\" is critical and cannot be stopped — {entry.SafetyDescription}"] = "⛔ \"{entry.DisplayName}\" é crítico e não pode ser parado — {entry.SafetyDescription}",
        ["Stop service \"{entry.DisplayName}\"?  This may affect system functionality."] = "Parar o serviço \"{entry.DisplayName}\"? Isso pode afetar funcionalidades do sistema.",
        ["Stop service failed: {ex.Message}"] = "Falha ao parar o serviço: {ex.Message}",
        ["⛔ \"{entry.DisplayName}\" is critical and cannot be disabled — {entry.SafetyDescription}"] = "⛔ \"{entry.DisplayName}\" é crítico e não pode ser desativado — {entry.SafetyDescription}",
        ["Disable service \"{entry.DisplayName}\"?  This prevents the service from starting automatically."] = "Desativar o serviço \"{entry.DisplayName}\"? Isso impede que ele inicie automaticamente.",
        ["Disable service failed: {ex.Message}"] = "Falha ao desativar o serviço: {ex.Message}",
        ["Enable service failed: {ex.Message}"] = "Falha ao ativar o serviço: {ex.Message}",
        ["Auto-purged — available RAM was below {ThresholdMb:F0} MB."] = "Liberação automática concluída — a RAM disponível estava abaixo de {ThresholdMb:F0} MB.",
        ["Purging standby list…"] = "Liberando memória em espera…",
        ["{EnabledCount} enabled · {DisabledCount} disabled · {TotalCount} total"] = "{EnabledCount} ativado(s) · {DisabledCount} desativado(s) · {TotalCount} total",
        ["{result.FixName} did not complete — see the output for details."] = "{result.FixName} não foi concluído — consulte a saída para detalhes.",
        ["Opened User Accounts (netplwiz). Untick \"Users must enter a user name and password\" to enable auto sign-in."] = "Contas de Usuário (netplwiz) aberto. Desmarque \"Os usuários devem digitar um nome de usuário e uma senha\" para ativar login automático.",
        ["OS {snap.Os.Caption}  —  CPU {snap.Cpu.Name} ({snap.Cpu.Cores}c/{snap.Cpu.LogicalProcessors}t)  —  RAM {snap.Memory.UsedGB:0.0}/{snap.Memory.TotalGB:0.0} GB  —  Disks {snap.Disks.Count}"] = "Windows {snap.Os.Caption} — CPU {snap.Cpu.Name} ({snap.Cpu.Cores}c/{snap.Cpu.LogicalProcessors}t) — RAM {snap.Memory.UsedGB:0.0}/{snap.Memory.TotalGB:0.0} GB — Discos {snap.Disks.Count}",
        ["Scan at {snap.CapturedAt:HH:mm:ss}"] = "Análise às {snap.CapturedAt:HH:mm:ss}",
        ["{snap.Disks.Count} disks, {snap.Memory.Modules.Count} RAM modules"] = "{snap.Disks.Count} disco(s), {snap.Memory.Modules.Count} módulo(s) de RAM",
        ["Couldn't copy: the clipboard is in use."] = "Não foi possível copiar: a área de transferência está em uso.",
        ["Drive enumeration failed: {ex.Message}"] = "Falha ao listar unidades: {ex.Message}",
        ["CheckDiskHealth failed: {ex.Message}"] = "Falha ao verificar a saúde dos discos: {ex.Message}",
        ["CheckMemoryErrors failed: {ex.Message}"] = "Falha ao verificar erros de memória: {ex.Message}",
        ["[{i + 1}/{selected.Count}] Scanning {d.Letter} — {d.Label}"] = "[{i + 1}/{selected.Count}] Analisando {d.Letter} — {d.Label}",
        ["Error on {driveLetter}: {ex.Message}"] = "Erro em {driveLetter}: {ex.Message}",
        ["Couldn't copy: the clipboard is in use by another application."] = "Não foi possível copiar: a área de transferência está sendo usada por outro aplicativo.",
        ["Couldn't change \"{task.Name}\" — this usually needs administrator rights."] = "Não foi possível alterar \"{task.Name}\" — normalmente isso exige direitos de administrador.",
        ["{Essential.Count} essential · {Advanced.Count} advanced tweak(s). Tick the ones you want, then Apply or Undo."] = "{Essential.Count} essencial(is) · {Advanced.Count} ajuste(s) avançado(s). Marque os desejados e use Aplicar ou Desfazer.",
        ["Querying winget list…"] = "Consultando lista do WinGet…",
        ["PSWindowsUpdate import failed: $($_.Exception.Message)"] = "Falha ao importar PSWindowsUpdate: $($_.Exception.Message)",
        ["PSWindowsUpdate history query failed: $($_.Exception.Message)"] = "Falha ao consultar o histórico do PSWindowsUpdate: $($_.Exception.Message)",
        ["Changing update policy requires administrator rights — use \"Run as administrator\"."] = "Alterar a política de atualizações exige direitos de administrador — use \"Executar como administrador\".",
        ["{UpdateCount} updates found"] = "{UpdateCount} atualizações encontradas",
        ["Windows Update Agent error: 0x{ex.HResult:X8}"] = "Erro do Agente do Windows Update: 0x{ex.HResult:X8}",
        ["{UpdateCount} history entries."] = "{UpdateCount} entradas no histórico.",
        ["{UpdateCount} history entries"] = "{UpdateCount} entradas no histórico",
        ["WUA error: 0x{ex.HResult:X8}"] = "Erro WUA: 0x{ex.HResult:X8}",
    };

    public static bool TryTranslate(string? text, out string translated)
    {
        translated = text ?? string.Empty;
        if (string.IsNullOrWhiteSpace(text)) return false;
        var trimmed = text.Trim();
        if (!Exact.TryGetValue(trimmed, out var value)) return false;
        var leading = text.Length - text.TrimStart().Length;
        var trailing = text.Length - text.TrimEnd().Length;
        translated = new string(' ', leading) + value + new string(' ', trailing);
        return true;
    }
}
