// Optimize · navigation, shell and final pt-BR coverage
// Original project: laurentiu021/SystemManager · MIT License

namespace SysManager.Services;

public static class PtBrMigrationCatalog6
{
    private static readonly Dictionary<string, string> Exact = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Error:"] = "Erro:",
        ["SysManager"] = "Optimize",
        ["System toolkit"] = "Ferramentas do sistema",
        ["PREVIEW"] = "PRÉVIA",
        ["Administrator"] = "Administrador",
        ["Standard user"] = "Usuário padrão",
        ["Dashboard"] = "Painel",
        ["System"] = "Sistema",
        ["System Health"] = "Saúde do sistema",
        ["Windows Update"] = "Windows Update",
        ["Performance Mode"] = "Modo de desempenho",
        ["Services"] = "Serviços",
        ["Startup Manager"] = "Gerenciador de inicialização",
        ["Windows Features"] = "Recursos do Windows",
        ["Restore Points"] = "Pontos de restauração",
        ["Task Scheduler"] = "Agendador de tarefas",
        ["Boot Analyzer"] = "Análise de inicialização",
        ["System Fixes"] = "Reparos do sistema",
        ["Tweaks Hub"] = "Central de ajustes",
        ["Gaming & Profiles"] = "Jogos e perfis",
        ["Gaming Profile"] = "Perfil para jogos",
        ["Standby List Cleaner"] = "Limpeza de memória em espera",
        ["Timer Resolution"] = "Resolução do temporizador",
        ["CPU Core Affinity"] = "Afinidade dos núcleos da CPU",
        ["Display Profiles"] = "Perfis de vídeo",
        ["Monitor"] = "Monitoramento",
        ["Process Manager"] = "Gerenciador de processos",
        ["Resource History"] = "Histórico de recursos",
        ["Camera/Mic/Location"] = "Câmera/Microfone/Localização",
        ["App Alerts"] = "Alertas de aplicativos",
        ["File Lock Detector"] = "Detector de arquivos bloqueados",
        ["Settings Watchdog"] = "Monitor de configurações",
        ["Bandwidth Monitor"] = "Monitor de largura de banda",
        ["Cleanup"] = "Limpeza",
        ["Quick Cleanup"] = "Limpeza rápida",
        ["Deep Cleanup"] = "Limpeza profunda",
        ["Shortcut Cleaner"] = "Limpeza de atalhos",
        ["Scheduled Maintenance"] = "Manutenção agendada",
        ["Storage"] = "Armazenamento",
        ["Disk Analyzer"] = "Analisador de disco",
        ["Duplicate Finder"] = "Localizador de duplicados",
        ["Network"] = "Rede",
        ["Speed Test"] = "Teste de velocidade",
        ["Network Repair"] = "Reparo de rede",
        ["DNS & Hosts"] = "DNS e hosts",
        ["Apps"] = "Aplicativos",
        ["App Updates"] = "Atualizações de aplicativos",
        ["Bulk Installer"] = "Instalador em lote",
        ["Uninstaller"] = "Desinstalador",
        ["Privacy & Security"] = "Privacidade e segurança",
        ["Privacy & Telemetry"] = "Privacidade e telemetria",
        ["File Shredder"] = "Exclusão segura de arquivos",
        ["App Blocker"] = "Bloqueador de aplicativos",
        ["Debloater & Ads"] = "Remoção de bloatware e anúncios",
        ["Browser Cleaner"] = "Limpeza de navegadores",
        ["Edge/OneDrive Remover"] = "Removedor do Edge/OneDrive",
        ["Defender Tweaks"] = "Ajustes do Defender",
        ["Notification Blocker"] = "Bloqueador de notificações",
        ["Customization"] = "Personalização",
        ["Context Menu"] = "Menu de contexto",
        ["Dark Mode Scheduler"] = "Agendador de modo escuro",
        ["Volume Control"] = "Controle de volume",
        ["Info"] = "Informações",
        ["Drivers"] = "Drivers",
        ["Battery Health"] = "Saúde da bateria",
        ["System Logs"] = "Logs do sistema",
        ["System Report"] = "Relatório do sistema",
        ["Legacy Panels"] = "Painéis clássicos",
        ["About"] = "Sobre",
        ["Advanced"] = "Avançado",
        ["Profile Export/Import"] = "Exportar/Importar perfil",
        ["CLI Interface"] = "Interface de linha de comando",
        ["Environment Variables"] = "Variáveis de ambiente",

        // Group subtitles/tooltips are generated by joining the original labels, so they need
        // full-string entries rather than relying on a source scanner to discover them.
        ["System Health · Windows Update · Performance Mode · Services · Startup Manager · Windows Features · Restore Points · Task Scheduler · Boot Analyzer · System Fixes · Tweaks Hub"] =
            "Saúde do sistema · Windows Update · Modo de desempenho · Serviços · Gerenciador de inicialização · Recursos do Windows · Pontos de restauração · Agendador de tarefas · Análise de inicialização · Reparos do sistema · Central de ajustes",
        ["Gaming Profile · Standby List Cleaner · Timer Resolution · CPU Core Affinity · Display Profiles"] =
            "Perfil para jogos · Limpeza de memória em espera · Resolução do temporizador · Afinidade dos núcleos da CPU · Perfis de vídeo",
        ["Process Manager · Resource History · Camera/Mic/Location · App Alerts · File Lock Detector · Settings Watchdog · Bandwidth Monitor"] =
            "Gerenciador de processos · Histórico de recursos · Câmera/Microfone/Localização · Alertas de aplicativos · Detector de arquivos bloqueados · Monitor de configurações · Monitor de largura de banda",
        ["Quick Cleanup · Deep Cleanup · Shortcut Cleaner · Scheduled Maintenance"] =
            "Limpeza rápida · Limpeza profunda · Limpeza de atalhos · Manutenção agendada",
        ["Disk Analyzer · Duplicate Finder"] = "Analisador de disco · Localizador de duplicados",
        ["Ping · Traceroute · Speed Test · Network Repair · DNS & Hosts"] =
            "Ping · Traceroute · Teste de velocidade · Reparo de rede · DNS e hosts",
        ["App Updates · Bulk Installer · Uninstaller"] =
            "Atualizações de aplicativos · Instalador em lote · Desinstalador",
        ["Privacy & Telemetry · File Shredder · App Blocker · Debloater & Ads · Browser Cleaner · Edge/OneDrive Remover · Defender Tweaks · Notification Blocker"] =
            "Privacidade e telemetria · Exclusão segura de arquivos · Bloqueador de aplicativos · Remoção de bloatware e anúncios · Limpeza de navegadores · Removedor do Edge/OneDrive · Ajustes do Defender · Bloqueador de notificações",
        ["Context Menu · Dark Mode Scheduler · Volume Control"] =
            "Menu de contexto · Agendador de modo escuro · Controle de volume",
        ["Drivers · Battery Health · System Logs · System Report · Legacy Panels · About"] =
            "Drivers · Saúde da bateria · Logs do sistema · Relatório do sistema · Painéis clássicos · Sobre",
        ["Profile Export/Import · CLI Interface · Environment Variables"] =
            "Exportar/Importar perfil · Interface de linha de comando · Variáveis de ambiente",
    };

    public static bool TryTranslate(string? text, out string translated)
    {
        translated = text ?? string.Empty;
        if (string.IsNullOrWhiteSpace(text)) return false;
        var trimmed = text.Trim();
        if (!Exact.TryGetValue(trimmed, out var value)) return false;
        var leading = text.Length - text.TrimStart().Length;
        var trailing = text.Length - text.TrimEnd().Length;
        translated = new string(' ', leading) + value + new string(' ', trailing);
        return true;
    }
}
